# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8a593da95d21ff9915d765666916fd6532cf5f6df9e13e2bdf08cd7be12f1e361722faf5d62e4994ee96ce8e6024c5ee3e00e50b2f67264e5d73fa4545e0313

test:
  secret_key_base: f601be48b46fc9c32a5f17733052b1ac2a42e4945de8df09c97530fc97da8004fa1c8c0641584e7430187715e3718c0173017bb817ca70832d1a653404510c5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
